### ISSUE TITLE
Error al crear una configuración (Catalogo configuraciones)

### ISSUE THREAD

**Issue by ahernandez-developer** [ahernandez-developer/sofa-master-erp#28]

**Comment by ahernandez-developer** [comment]
![image](https://user-images.githubusercontent.com/59542869/110708606-2b93bc80-81b8-11eb-9cba-9c282a2f481a.png)

**Comment by LeyvaF** [comment]
Alan, hice un cambio en el campo TariffPercentage de la tabla de setups, estaba como decimal, debe de ser Varchar, creo que por eso te hace ruido a ti, creo que tienes que actualizar tu base de datos.
