### ISSUE TITLE
Error al crear catalogo de clientes en el apartado de direcciones.

### ISSUE THREAD

**Issue by ahernandez-developer** [ahernandez-developer/sofa-master-erp#46]

**Comment by ahernandez-developer** [comment]
![image](https://user-images.githubusercontent.com/59542869/113487683-564afb00-946e-11eb-8c0a-29a0c58a0df9.png)

**Comment by ahernandez-developer** [comment]
![image](https://user-images.githubusercontent.com/59542869/113487693-5fd46300-946e-11eb-81ec-421ebe806fef.png)
No redirecciona a la pagina del listado

**Comment by ahernandez-developer** [comment]
![image](https://user-images.githubusercontent.com/59542869/113487705-72e73300-946e-11eb-8330-1b9012b26c37.png)
Nombre y codigo no son campos no obligatorios

**Comment by ahernandez-developer** [comment]
![image](https://user-images.githubusercontent.com/59542869/113487764-bc378280-946e-11eb-840d-5902f4c023c6.png)
Error al agregar una direaccion solo con los campos olbigatorios

**Comment by ahernandez-developer** [comment]
![image](https://user-images.githubusercontent.com/59542869/113487841-3ec04200-946f-11eb-9045-f1a2beb58f71.png)
Al presionar el boton de cancelar me regresa al listado de clientes en lugar de al listado de direcciones

**Comment by ahernandez-developer** [comment]
![image](https://user-images.githubusercontent.com/59542869/113489580-dd51a080-9479-11eb-8d01-ec16be9216f1.png)
Me resulta poco intuitivo la forma de mostrar los vendedores. y los productos que tiene asignado cada vendedor. Tal vez seria conveniente revisar con Yhamil una forma mas intuitiva de mostrar esta información

**Comment by Marcos-Cerrillo** [comment]
entendido lo del mensaje de vendedores prob un multi select, as por los demas bugs ya se parcharon por lo visto ese bad request era dado por un error en un campo que era necesario pero no validado
