### ISSUE TITLE
Catalogo de proveedores no tiene validaciones 

### ISSUE THREAD

**Issue by ahernandez-developer** [ahernandez-developer/sofa-master-erp#50]

**Comment by ahernandez-developer** [comment]
![image](https://user-images.githubusercontent.com/59542869/113489656-53ee9e00-947a-11eb-8d55-7094dde931b8.png)
Error al crear un proveedor ya que no tienen validaciones

![image](https://user-images.githubusercontent.com/59542869/113489697-7d0f2e80-947a-11eb-85db-76207ebcc368.png)
Agregar alguna validación sobre el tipo de dato. Al completar todos los campos sigue dando error, me imagino que algunos deben ser números.

**Comment by Marcos-Cerrillo** [comment]
Validationsm ,sellers, suppliers added.... i completely forgot lol

**Comment by ahernandez-developer** [comment]
Sigo sin poder agregar un proveedor y estos dos son los únicos campos que me muestra validación.
![image](https://user-images.githubusercontent.com/59542869/113652531-29a30900-9651-11eb-8fc4-78d52bae8da7.png)

**Comment by yhamilsama21** [comment]
@Marcos-Cerrillo

**Comment by yhamilsama21** [comment]
Los campos a validar como obligatorios son los siguientes:

- Nombre
- Código
- RFC
- Empresa
- Pais
- Estado
- Ciudad
- IVA

**Comment by yhamilsama21** [comment]
1. Agregar select en monedas para seleccionar las opciones  **USD o Peso Mexicano**
2. Agregar Select en campo IVA (%) para seleccionar las opciones **8% o 16%**
