### ISSUE TITLE
Error al editar un defecto

### ISSUE THREAD

**Issue by ahernandez-developer** [ahernandez-developer/sofa-master-erp#51]

**Comment by ahernandez-developer** [comment]
![image](https://user-images.githubusercontent.com/59542869/113489823-4259c600-947b-11eb-948c-6f35b8d817fd.png)
Cuando actualizo un defecto y cambio el departamento no surte efecto el cambio. sigue manteniendo el mismo departamento que cuando es creo el defecto

**Comment by LeyvaF** [comment]
Corregido.
