### ISSUE TITLE
Error al editar un producto

### ISSUE THREAD

**Issue by ahernandez-developer** [ahernandez-developer/sofa-master-erp#52]

**Comment by ahernandez-developer** [comment]
![image](https://user-images.githubusercontent.com/59542869/113489900-beeca480-947b-11eb-8308-2278b200d46a.png)
Parece ser que al actualizar una relacion(un dropdown) aparece un error.

![image](https://user-images.githubusercontent.com/59542869/113489923-de83cd00-947b-11eb-8654-6864839d549f.png)
Hay que investigar como es que se actualiza un relación en entity framework. se debe enviar el objeto completo. no solo el Id de la realación desde vue. o modificar la logica del controlador para con el Id de la realacion enviado actualizar el campo id de la tabla.


https://docs.microsoft.com/es-es/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/updating-related-data-with-the-entity-framework-in-an-asp-net-mvc-application

**Comment by LeyvaF** [comment]
![image](https://user-images.githubusercontent.com/77205213/113624603-1413ec00-961d-11eb-85cf-19f5fdacd2fa.png)

ya quedo corregido pero salio el error del DATETIME y pero lo soluciona pasandolos a DATETIME2
