### ISSUE TITLE
Catalogo de clientes, faltan validaciones.

### ISSUE THREAD

**Issue by ahernandez-developer** [ahernandez-developer/sofa-master-erp#54]

**Comment by ahernandez-developer** [comment]
![image](https://user-images.githubusercontent.com/59542869/113652045-50ad0b00-9650-11eb-867f-de9a2ef61f1c.png)
Ya me permite crear clientes con la resolución de este bug https://github.com/ahernandez-developer/sofa-master-erp/issues/46., pero me permite crear clientes sin nombre y dejar las direcciones vacías si no las ingreso por lo que genera registros con los datos en blanco en direcciones.
![image](https://user-images.githubusercontent.com/59542869/113652309-c44f1800-9650-11eb-9492-2fc5135f975a.png)

Se que no tiene sentido ingresar una dirección vacía en cuanto a la lógica del negocio, pero debemos minimizar los errores de captura validando que estos campos sean requeridos o bien validando que si los campos son vacíos no se agregue el registro a la base de datos.

**Comment by yhamilsama21** [comment]
@Marcos-Cerrillo los campos a validar obligatorios son:

1. Nombre
2. Código
3. RFC/TAX ID

EN AMBAS DIRECCIONES

1. Dirección
2. Ciudad
3. Estado
4. Pais
5. Codigo Postal

Son datos necesarios para Facturacion.

**Comment by yhamilsama21** [comment]
@Marcos-Cerrillo 

1. Validar que no se agreguen numeros negativos en todos los campos que lleven numeros.
![image](https://user-images.githubusercontent.com/77205239/114083683-8af2f400-986c-11eb-8387-e10b3a9b15bf.png)

2.Validar que el codigo del Clinte y el Nombre no se repitan.

3. No puedes poner punto decimal en las cantidades que llevan numeros

4. No me permite poner numeros con el teclado numerico. 

5. Al agregar un vendedor se deben desplegar los vendedores dados de alta en el catálogo de vendedores.
