### ISSUE TITLE
Validaciónes Catalogos de Equipo de Protección, herramientas, refacciones y maquinaría.

### ISSUE THREAD

**Issue by yhamilsama21** [ahernandez-developer/sofa-master-erp#64]

**Comment by yhamilsama21** [comment]
1. Validar que no se repitan el Código y la descripción.
![image](https://user-images.githubusercontent.com/77205239/114089660-a57c9b80-9873-11eb-913a-f3be37bb84e1.png)

**Comment by ahernandez-developer** [comment]
Revisar la tarjeta de unidades de medida para ver un ejemplo
