### ISSUE TITLE
Validaciones Catalogo de Unidad de Medida

### ISSUE THREAD

**Issue by yhamilsama21** [ahernandez-developer/sofa-master-erp#73]

**Comment by ahernandez-developer** [comment]
![image](https://user-images.githubusercontent.com/59542869/114123924-8c461000-98b0-11eb-9c63-7c3160b863c0.png)

![image](https://user-images.githubusercontent.com/59542869/114123832-6456ac80-98b0-11eb-99df-2a276855ddf0.png)
Se agrego una validación sencilla en caso de que existan una unidad de medida que contenga un código o  una descripción registrada previamente.

**Comment by ahernandez-developer** [comment]
Codigo de Vue para la validación
![image](https://user-images.githubusercontent.com/59542869/114124077-d5965f80-98b0-11eb-83ad-f92d6841603e.png)
Código de ..NET para la validación
![image](https://user-images.githubusercontent.com/59542869/114124214-2a39da80-98b1-11eb-857f-d441de7155c6.png)

El código se encuentra en ambos branch master

**Comment by ahernandez-developer** [comment]
Revisar si esta validación funciona para el negocio, o si debe validarse de otra forma.
